apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: vprofile
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: vprofile
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: memcached

  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: memcached
