apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: vprofile
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: vprofile
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: vprofile-local
  volumeMode: Filesystem
  volumeName: vprofile-mariadb-pv

  resources:
    requests:
      storage: 10Gi
