apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: vprofile
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: vprofile
spec:
  clusterIP: None
  publishNotReadyAddresses: true

  selector:
    app.kubernetes.io/name: rabbitmq

  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: vprofile
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: vprofile
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: rabbitmq

  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
