apiVersion: v1
kind: Service
metadata:
  name: vprofile-app
  namespace: vprofile
  labels:
    app.kubernetes.io/name: vprofile-app
    app.kubernetes.io/part-of: vprofile

spec:
  type: NodePort

  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  selector:
    app.kubernetes.io/name: vprofile-app

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30080
